cc_library(
    visibility = ['PUBLIC'],
    name = 'uuid',
    srcs = 'uuid.cpp',
    deps = ['//thirdparty/toft/base/string:string'],
)

#cc_benchmark(
#    name = 'uuid_benchmark',
#    srcs = 'uuid_benchmark.cpp',
#    deps = [':uuid'],
#)
